# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="powerline"
#ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="false"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

# User configuration

POWERLINE_RIGHT_B="none"

POWERLINE_PATH="short"

POWERLINE_HIDE_USER_NAME="true"
# POWERLINE_SHORT_HOST_NAME="true"

POWERLINE_DETECT_SSH="true"
POWERLINE_SHOW_GIT_ON_RIGHT="true"


# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# add autosuggestions
#source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

# configuration for autosuggestion
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=yellow'

# Keybindings
bindkey -v

export EDITOR='nvim'
#export VISUAL='nvim'

# Here is some etra to add More dirextory to the PATH variable
export PATH="$PATH:"~/scripts""
export PATH="$PATH:"~/.local/bin""

alias ncdu='ncdu --color dark-bg'

# Add alias for tmux
alias tmux='tmux -2 -f /home/teubl/.tmux.conf'

#TODO run fbterm only if you def terminal is linux
case "$TERM" in
    xterm*)
        if [ -e /usr/share/terminfo/x/xterm-256color ]; then
            export TERM=xterm-256color
        elif [ -e /usr/share/terminfo/x/xterm-color ]; then
            export TERM=xterm-color;
        else
            export TERM=xterm
        fi
        ;;
    linux)
        #FBTERM=1 fbterm
        #[ -n "$FBTERM" ] && export TERM=fbterm
        ;;
esac

# run a new session of tmux right after the fbterm
# tmux attach &> /dev/null # would allow only one session per user

# Useful if using the same file on more  devices
#if ! [[ -n $SSH_CONNECTION ]]; then
#    tmux
#fi

# alias for battery
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "time\ to\ "'
alias bat_raw='upower -i /org/freedesktop/UPower/devices/battery_BAT0'

# Alias for copy with rSunz
alias rsync='rsync -vah --progress'

# Starts SSH-agent after login. NOTE: This is not the best sollution, but works!
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(ssh-agent)" > /dev/null
fi

ssh-add ~/.ssh/github 2> /dev/null

alias vim='nvim'
alias dmesg='dmesg -e -H -c'

#set -o ignoreeof
