# Path to your oh-my-zsh installation.
export ZSH=$HOME/progs/tools/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
 ZSH_THEME="powerline"
# ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
 DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
 ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

POWERLINE_RIGHT_B="none"

POWERLINE_PATH="short"
POWERLINE_CUSTOM_CURRENT_PATH="%1~"

# POWERLINE_HIDE_USER_NAME="true"
POWERLINE_SHORT_HOST_NAME="true"

POWERLINE_DETECT_SSH="true"
POWERLINE_SHOW_GIT_ON_RIGHT="true"


# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Here is some etra to add More dirextory to the PATH variable

# Add valgrind to path
if [ -d "$HOME/progs/tools/valgrind-3.12.0" ] ; then
    PATH="$PATH:$HOME/progs/tools/valgrind-3.12.0" 
fi

# Add valgrind to path
if [ -d "$HOME/progs/tools/gcc-arm-none-eabi-5_4-2016q3" ] ; then
    PATH="$PATH:$HOME/progs/tools/gcc-arm-none-eabi-5_4-2016q3/bin" 
fi

PATH="$PATH:$HOME/RPI/toolchain/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin"

export PATH="$PATH:"~/scripts""
export PATH="$PATH:"/opt/microchip/xc16/v1.30/bin""

#alias clc='clear'
alias naut='nautilus . &'

# alias for python 3.xx
# alias python='python3.6'
# alias pip='pip3'

# Add alias for tmux
# alias tmux='tmux -2'
# alias tmux='TERM=screen-256color-bce tmux -2 -f /home/teubl/.tmux.conf'
alias tmux='tmux -2 -f /home/teubl/.tmux.conf'

#TODO run fbterm only if you def terminal is linux
case "$TERM" in
    xterm*)
        if [ -e /usr/share/terminfo/x/xterm-256color ]; then
            export TERM=xterm-256color
        elif [ -e /usr/share/terminfo/x/xterm-color ]; then
            export TERM=xterm-color;
        else
            export TERM=xterm
        fi
        ;;
    linux)
        FBTERM=1 fbterm 
        [ -n "$FBTERM" ] && export TERM=fbterm
        ;;
esac

# run a new session of tmux right after the fbterm
# tmux attach &> /dev/null # would allow only one session per user
tmux 

# alias for battery
alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "time\ to\ "'
alias bat_raw='upower -i /org/freedesktop/UPower/devices/battery_BAT0'

