#!/bin/bash
#
# A script file to update VIM for with the right dependencies

if [ "--v" == $1 ]; then
    DEBUG=1
else
    DEBUG=0
fi

# Find the root directory of the project
while [ "dotfiles" != "${PWD##*/}" ]; do
    # to print to stdout, quoted for use as shell input
    if [ $DEBUG == 1 ]; then
        printf 'Looking for the root directory of the project..\n'
        printf '%q\n' "${PWD#*/}" 
    fi
    cd ..
done

# Check that the offical VIM repo is cloned near this project

printf 'Updateing VIM...'
cd ..

if [ -d "vim" ]; then
    cd ./vim
else
    git clone https://github.com/vim/vim.git
    cd ./vim
fi

# Do the actual update
git fetch
git pull


# instal dependencies
sudo apt install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python3.6-dev \
    python3-dev ruby-dev lua5.1 liblua5.1-dev libperl-dev git

# remove old version
sudo apt remove vim vim-runtime gvim vim-tiny vim-common 
    vim-gui-common vim-nox

# set the right configuration
./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-python3interp=yes \
            --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu \
            --enable-perlinterp=yes \
            --enable-luainterp=yes \
            --enable-gui=gtk2 \
            --enable-cscope \
            --prefix=/usr/local


sudo make VIMRUNTIMEDIR=/usr/local/share/vim/vim80


# install the program
sudo make install

# Install the plugins
vim +PluginInstall +qall
# Update the plugins
vim +PluginInstall +qall

# Set alternative - so the system will use vim almost as default editor
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/vim 1
sudo update-alternatives --set editor /usr/bin/vim
sudo update-alternatives --install /usr/bin/vi vi /usr/bin/vim 1
sudo update-alternatives --set vi /usr/bin/vim



